version: '3.9'
services:
  mongo:
    image: mongo:4-focal
    ports:
      - 27017:27017
  kanban:
    image: kanban
    restart: always
    environment:
      - HTTP_PORT=9090
      - MONGODB_URI=mongodb://mongo/deno
    ports:
      - 9090:9090