---
- get_url:
    url: "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64"
    dest: ~/docker-compose
- ansible.builtin.shell:
    cmd: mv ~/docker-compose /usr/local/bin/docker-compose
- ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    mode: +x
